services:
  # API service
  uniconnect-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: uniconnect-api
    ports:
      - "8080:80"
      - "8443:443"
      - "5678:5678" # VS Code debugger
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=uniconnect;Username=uniconnect;Password=uniconnect_password
      - Redis__Configuration=redis:6379
      - MinioSettings__Endpoint=minio:9000
      - MinioSettings__AccessKey=minioadmin
      - MinioSettings__SecretKey=minioadmin
      - MinioSettings__UseSSL=false
      - JwtSettings__SecretKey=super_secret_key_for_development_only_change_in_production
      - JwtSettings__Issuer=UniConnect
      - JwtSettings__Audience=UniConnect
      - JwtSettings__ExpiryMinutes=60
      - EmailSettings__SmtpServer=mailhog
      - EmailSettings__SmtpPort=1025
      - EmailSettings__EnableSsl=false
      - EmailSettings__FromEmail=noreply@uniconnect.com
      - EmailSettings__FromName=UniConnect
      - ASPNETCORE_URLS=http://+:80
    networks:
      - uniconnect-network
    volumes:
      # Use correct path mapping based on your folder structure
      - ./src/UniConnect.API:/app/src/UniConnect.API
      - ./src/UniConnect.Application:/app/src/UniConnect.Application
      - ./src/UniConnect.Domain:/app/src/UniConnect.Domain
      - ./src/UniConnect.Infrastructure:/app/src/UniConnect.Infrastructure
      - ./src/UniConnect.Identity:/app/src/UniConnect.Identity
      - ./UniConnect.sln:/app/UniConnect.sln
      - ./logs:/app/logs
    restart: always

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: uniconnect-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=uniconnect
      - POSTGRES_PASSWORD=uniconnect_password
      - POSTGRES_DB=uniconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uniconnect-network
    restart: always

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: uniconnect-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uniconnect-network
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: uniconnect-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - uniconnect-network
    command: server /data --console-address ":9001"
    restart: always

  # MailHog for Email Testing
  mailhog:
    image: mailhog/mailhog
    container_name: uniconnect-mailhog
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    networks:
      - uniconnect-network
    restart: always

# Networks
networks:
  uniconnect-network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
  redis_data:
  minio_data:
