import 'package:flutter/material.dart';

// Light color scheme based on the design system in README
final lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: const Color(0xFF2563EB),
  onPrimary: Colors.white,
  primaryContainer: const Color(0xFFDDEBFF),
  onPrimaryContainer: const Color(0xFF001D36),
  secondary: const Color(0xFF10B981),
  onSecondary: Colors.white,
  secondaryContainer: const Color(0xFFB5F7D7),
  onSecondaryContainer: const Color(0xFF00210E),
  tertiary: const Color(0xFFF59E0B),
  onTertiary: Colors.white,
  tertiaryContainer: const Color(0xFFFFDDB4),
  onTertiaryContainer: const Color(0xFF2E1800),
  error: const Color(0xFFEF4444),
  onError: Colors.white,
  errorContainer: const Color(0xFFFFDAD6),
  onErrorContainer: const Color(0xFF410002),
  surface: const Color(0xFFF3F4F6),
  onSurface: const Color(0xFF111827),
  surfaceContainerHighest: const Color(0xFFE7E0EC),
  onSurfaceVariant: const Color(0xFF4B5563),
  outline: const Color(0xFFE5E7EB),
  outlineVariant: const Color(0xFFE5E7EB),
  shadow: const Color(0xFF000000),
  scrim: const Color(0xFF000000),
  inverseSurface: const Color(0xFF111827),
  onInverseSurface: Colors.white,
  inversePrimary: const Color(0xFFADD2FF),
  surfaceTint: const Color(0xFF2563EB),
);

// Dark color scheme based on the design system in README
final darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: const Color(0xFF93C6FF),
  onPrimary: const Color(0xFF003258),
  primaryContainer: const Color(0xFF004B7D),
  onPrimaryContainer: const Color(0xFFD1E4FF),
  secondary: const Color(0xFF7DDEB8),
  onSecondary: const Color(0xFF003825),
  secondaryContainer: const Color(0xFF005138),
  onSecondaryContainer: const Color(0xFF9AF6D1),
  tertiary: const Color(0xFFFFB951),
  onTertiary: const Color(0xFF4A2800),
  tertiaryContainer: const Color(0xFF693C00),
  onTertiaryContainer: const Color(0xFFFFDCC0),
  error: const Color(0xFFFFB4AB),
  onError: const Color(0xFF690005),
  errorContainer: const Color(0xFF93000A),
  onErrorContainer: const Color(0xFFFFDAD6),
  surface: const Color(0xFF1F2937),
  onSurface: const Color(0xFFE1E1E1),
  surfaceContainerHighest: const Color(0xFF4A454F),
  onSurfaceVariant: const Color(0xFFCCC4D1),
  outline: const Color(0xFF9CA3AF),
  outlineVariant: const Color(0xFF4A454F),
  shadow: const Color(0xFF000000),
  scrim: const Color(0xFF000000),
  inverseSurface: const Color(0xFFE1E1E1),
  onInverseSurface: const Color(0xFF303031),
  inversePrimary: const Color(0xFF0062A0),
  surfaceTint: const Color(0xFF93C6FF),
);
